登录页面:
  登录页面_用户名的校验01:  # 正向
    表单数据:
      用户名: ${v_char}
      密码: admin123
      验证码: "12"
      记住我:
    验证字段_断言数据:  # 验证字段可以填多个, 断言字段也可以填多个
      - [{"v_char": "admin"}, {"assert_text": "hello"}]

  登录页面_用户名的校验02:  # 逆向的
    表单数据:
      用户名: ${v_char}
      密码: admin123
      验证码: "12"
      记住我:
    验证字段_断言数据:
      - [{"v_char": ""}, {"assert_text": "请输入您的用户名"}]
      - [{"v_char": "123"}, {"assert_text": "用户不存在"}]
      - [{"v_char": "tom01"}, {"assert_text": "用户不存在"}]

  登录页面_密码的校验01:  # 正向
    表单数据:
      用户名: admin
      密码: ${v_char}
      验证码: "12"
      记住我:
    验证字段_断言数据:
      - [{"v_char": ""}, {"assert_text": "请输入您的密码"}]

  登录页面_密码的校验02:  # 正向
    表单数据:
      用户名: admin
      密码: ${v_char}
      验证码: "12"
      记住我:
    验证字段_断言数据:
      - [{"v_char": ""}, {"assert_text": "请输入您的密码"}]
      - [{"v_char": "123"}, {"assert_text": "用户不存在"}]


