登录页面:
  资源路径: /login
  定位元素:
    用户名输入框: //*[@id="signupForm"]/input[1]
    密码输入框: //*[@id="signupForm"]/input[2]
    验证码输入框: //*[@id="signupForm"]/div[1]/div[1]/input
    验证码图片: //*[@id="signupForm"]/div[1]/div[2]/a/img
    记住我: //*[@id="rememberme"]
    登录按钮: //*[@id="btnSubmit"]

后台主页:
  资源路径: /index
  定位元素:
    侧边栏:
      首页: //*[@id="side-menu"]/li[2]/a/span[text()="首页"]
    右上角的个人图标:
      个人图标: //*[@id="page-wrapper"]/div[1]/nav/ul/li[4]/a/span
      退出登录按钮: //*[@id="page-wrapper"]/div[1]/nav/ul/li[4]/ul/li[6]/a